### ISSUE TITLE
Warzone improvement

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#10]
<SX> But imo would be good to improve warzone a bit first as it is not very useful or interesting currently

Hedgehog: Oh ... warzone : put a mese dragon spawn point in there ....
As there is not much it can turn into mese blocks, other than your ships ....
And with an 10K HP you need either very powerful cannons, or team up with players.

sunkenhero: or trap into big pit?

Hedgehog: the Mese Dragon?  It can fly, so that wont work .

1hit: teleport in a bunch of ships to "cage it"?

Hedgehog: Player faction would probably come into play there .... Keep in mind : the dragon's teeth, claws, horns, tail, and roar are all lethal. Took me forever to craft the egg on the other server.

**Comment by Klaranth** [comment]
Closed. No interaction for 3+ weeks.

**Comment by S-S-X** [comment]
This is very relevant and comes up every few months, instead of closing this issue we should collect all existing ideas here and there's a lot of those.

**Comment by S-S-X** [comment]
Some discussions and ideas cherry picked from chat logs, this list is not even near complete discussion log and many good ideas are still buried somewhere under huge pile of unnecessary chat spam that is not talking about warzone improvements.

## 2020

_messages edited a bit to drop irrelevant stuff_
jessicara: netherite has got me thinking, thoughts on adding an extremely rare ore to warzone to give incentive to go there? one which makes weapons/tools slightly better? with some kinda preparation steps to get it usable, like compressor and/or centrifuge
jihuu: yes from me it could perhaps be called nividium
jessicara: think it might need a mob more dangerous than xenomorphs though? to keep the exploring to find it interesting
jihuu: space flies scary and dangerous
SX: there was idea about adding some more or less wrecked space ships with some equipment like hv machinery, cannons etc. to warzone. it would also be interesting if cannons would randomly actually shoot when you're close enough
SX: so station wreckages and alien ships, some asteroids with some rare ores would also fit nicely
jihuu: aliens
jessicara: yeah so, more alien models too. alien spawners
thomas18F: station wreckages WITH aliens in it xD
jihuu: thomas18F: working stations with aliens in them. if they are wreckages, the aliens probably abandoned them
jessicara: unless the aliens caused the wreckages
jessicara: maybe somewhere in the universe there will be a bunch of aliens sitting on a bench complaining about these alien humans stealing their jobs
jihuu: anyone seen the morlendor mobs in nssm mod?

jessicara: about issue 434 (armor making nearly immortal), maybe the armor would become more balanced if get around to adding more aliens which do enough damage not to get rounded down to zero all the time
jessicara: then fill warzone with these mobs
BuckarooBanzai: jessicara: filling warzone with dangerous mobs sounds good, but there is no reason to get up there in the first place :P
BuckarooBanzai: there is currently no incentive to go to the warzone, no resources, nothing to see (yet)
jessicara: maybe if bring over crystal it could be restricted to warzone
BuckarooBanzai: "over crystal"
calculon: maybe the fun to capture them could make warzone attractive :)

## 2021

SX: Some generated stuff would still be nice to have, and possibly some way more dangerous mobs.
SX: I think I still like space station / ship wrecks with aliens inside, possibly with those still active automated defence systems like space cannons that you could get but those would also shoot at you when you approach.

SX: Actually would be interesting to do thing like that without actually using mapgen but randomly placing schematics to large enough empty space... section of warzone defended by aliens that jump in with their ships and shoot at you :)
FeXoR: SX, 1hit: Well, if the alien ships shoot back placing them into the warzone makes sense so the player at least has some risk ... though I guess that requires at least some rudimentary aito piloting for the player could just go in without a ship first.

## 2022

Huhhila: [#47] instead of outright closing 47, tag it controversial and/or limit the effects to warzone and above or similar.
Huhhila: (for disease that doesn't happen to be capable of surviving on earth, which would be more newbie-friendly approach)
Huhhila: (or one that goes to hibernation mode when exposed to earth... extraterrestrial diseases can be applied quite liberal amounts of scifi since pretty much nothing is known about such anyway)

FeXoR: I think dragons in the warzone would fit, yes. The mesedragon ... wasn't that something that kept crashing SurvivalWorld(LandOfSurvivors?)? :p
Klaranth: Would adding a Mese dragon to live in the warzone be a good idea ? ( #10)

SX: And again warzone would be so much better if there actually was some valuable stuff and somewhat more dangerous environment even if you're alone there... like those alien ships or something else that popped up before..

**Comment by OgelGames** [comment]
Closing in favor of #335 (much more discussion there)
