### ISSUE TITLE
HV Hydro 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#106]
Is there a way to create HV Hydro? Perhaps make it sized 3x3x3 nodes, with the central vertical axis empty ( for either use of a cable, or a column of water). 

Making it more powerful, yet sizable as a downside to it.

**Comment by eshattow** [comment]
MV Hydro output each side:
0% 0EU default:water_source, param2:0
33% 600EU default:water_flowing, param2:15

8% 160EU default:water_source, param2:4

default:water_source, param2:4
default:water_source, param2:4
default:water_source, param2:4
default:water_source, param2:4
default:water_source, param2:4
default:water_source, param2:4
default:water_source, param2:4
default:water_source, param2:4
default:water_source, param2:4
default:water_source, param2:4
default:water_source, param2:4
default:water_source, param2:4
default:water_source, param2:4
default:water_source, param2:4
default:water_source, param2:4



per side exposed to flowing water or 

MV Hydro is already kind of overpowered with the water param2:23 glitch where each face exposed to a source water block that has been rotated is then 51% efficient on the hydro machine. If that glitch gets resolved then it might actually be better to have a less-powerful HV hydro that needs fewer faces exposed to water, or the same amount of power HV compared with MV when adjusted but also more compact as the advantage. There is a norm in gameplay that MV should remain useful for some things (centrifuge, extractor, workshop, freezer, alloy furnace). Proposed the HV Hydro changes common build layout possibilities because of how supply converters are top-in bottom-out; it removes the need for supply converters to use Hydro for pure HV builds which is an advantage in itself.

MV Hydro outputs 600 EU per side of flowing water maximum 1800 EU; except when faced with two source water nodes (that have been rotated specially to param2:23) where it outputs or when faced with three flowing water.

HV Hydro could output 800 E

**Comment by eshattow** [comment]
5400 EU (4860EU after 10% loss of supply converter):
water - water - water
Hydro MV - Hydro MV - Hydro MV
water - water - water

4800EU:
Hydro HV - Hydro HV - Hydro HV
water - water - water
Hydro HV - Hydro HV - Hydro HV

That needs play testing for balance but if Hydro HV can produce maximum 800EU but it can do that with water on only one side, then I think it might be balanced. For the normal use case of 'default:water_flowing, param2:15' the Hydro HV should output 520EU only. That puts Hydro HV at 86% of comparable Hydro MV so slightly worse efficiency when factoring in a 10% loss of any converter; Also if you are using Hydro HV to power MV machines then you still need a converter and you incur the 10% loss and it is even more interesting to decide whether to use Hydro MV or Hydro HV.

However you do gain a huge advantage with Hydro HV as I am suggesting because it would build much more compactly (but at a very high cost to build much like HV Solar Array is quite the grind and costly to build).

**Comment by S-S-X** [comment]
> very high cost to build much like HV Solar Array is quite the grind and costly to build

That's one problem with simply trying to make more "expensive" recipes, it is not really possible. HV solars for example is not any problem making in thousands right away for some players while some players have a lot of problems making just one.

Simply increasing recipe expenses by very large amounts is not way to go alone, it will just make wealth gap between players way higher if very expensive thing provides way more efficient way to get more very expensive things.

We cannot just scale "end game" stuff vertically like that and keep all stages of game actually interesting, it needs to be way more complex than that.

**Comment by eshattow** [comment]
Clarifying that the very high cost comes from the recipe procession of requiring three of the previous unit i.e.:
stainless steel ingot - Hydro MV - stainless steel ingot
Hydro MV - High Voltage Transformer - Hydro MV
stainless steel ingot - HV Cable - stainless steel ingot

If you don't want the compactness of Hydro HV (considering no need for supply converter to output HV) then don't do that, as Hydro MV would produce more power and more affordable.

That's my take on it. I don't want some overpowered Hydro HV unit that is overly complicated. If we fix the water flowing Hydro bug then probably I would want 800EU 50% per side Hydro HV maximum total 1600EU with just normal flowing water. That would be an upgrade from the 600EU per side Hydro MV 33% but a lower total combined power.

**Comment by Klaranth** [comment]
Don't make HV less powerful than MV. Make it equal. 

With HV, there is no need for a converter, so more compact, and with the 10% loss gone.  That should be enough to want the HV over the MV.

**Comment by eshattow** [comment]
An example: I've made an r=4 jumpdrive ship using 220 Hydro MV nodes for power. Output measured at the MV Switching Station is 194.2 kEU without any rotated water block exploit (there are some 0% efficiency Hydro MV units in this configuration). There's room enough left over in that layout for 40 supply converters, plenty to cover the Hydro MV output upper limit of estimated 346.7 kEU MV if using rotated source water blocks. There's even some spots for a dozen Battery Boxes and a few machines, probably not enough machines to use all that power (!?) The example of a full uranium centrifuge setup requiring 238 kEU/s instantaneous or 122.5 kEU/s can easily be handled by this layout without any gimmicks or exploits, and it is fully able to jumpdrive.

What footprint does a nuclear reactor layout take up, and what is the output? but then you can't jumpdrive that  (I am limiting to r=4 for size comparison to a nuclear reactor, of course you could power jumpdrive a bigger radius to include nuclear reactor).

For the Hydro HV to make sense it should be less powerful than MV and gain a whole lot of layout options by removing the requirement for MV cable and supply converters in an all-HV setup. Think of those 40 supply converters on the Hydro MV layout, each needs cable above and below it is an enormous dead-space that would instead be possible to place Array HV Solar, or any machine with a vertical pipeworks connection. All of the cable strings on a Hydro HV layout could be used to connect machines! That would be a considerable increase in usefulness, even if the Hydro HV units were markedly worse output than Hydro MV counterpart. It's more interesting to me (whatever power output it is decided) what kind of layouts are possible, than to make some kind of ultimate power block. What could be the outcome is to just not use the supply converter at all, instead keeping an HV power source and an MV power source each.

I would rather say that if/when the rotated source water block Hydro MV exploit is closed, that we have an upgraded Hydro MV to do the same kind of layout possibilities. I want to like the idea for Hydro HV but it would have to be less powerful (than the Hydro MV) to be any fun.

**Comment by Klaranth** [comment]
Hedgehog 
An HV Hydro would only work well in-game if it has some drawbacks.  like being bulky to build, or when you need to use 16 MV Hydro while the output is less than that.
Fix the water glitch and be done with it. Make it so that the water can't be rotated.

Orekart 
The R4 jump ship I am making with Hydro MV is 300kEU before conversion losses
I don't even think nuclear can beat that. 
"Make it so the water can't be rotated" this breaks the whole game. Also breaks Hydro.

SX 
Hydro could easily check for actual flowing water but not seen that important so far, it would be better to fix this but most are not interested in such minor fix

**Comment by Klaranth** [comment]
Orekart 
Yeah it is not so easy to exploit, and it works normally with and without exploiting (there is no > 100% advantage). It's just more compact layout. I guess for the configuration of one side only adjacent to water there is an advantage because normally that would only be 33% efficient, but with the exploit that can be 51% efficient for one adjacent water.

**Comment by S-S-X** [comment]
Yes it is very true that completely maintenance free hydros are way too powerful currently and some rebalancing should probably be done in technic mod, one problem is that changing things will probably break some existing builds unless someone comes up with some clever ideas about balancing stuff.

Current state is not good and these mistakes should not be repeated or balance made worse by adding HV versions just like that, it clearly needs some extensive testing to find out what should be done and then think about what can be done without breaking everything.

**Comment by eshattow** [comment]
For other reference, r=5 is the smallest nuclear reactor jumpdrive ship possible 100kEU HV while the jumpdrive must be inside the reactor, but with r=6 you can fit four nuclear reactors and a jumpdrive in the center between reactors so 400kEU HV. That is focused on jumpdrive and able to survive vacuum just to be talking about equal things. Also noting Ruggila saying they have a no-exploits r=7 with one layer of checkerboard Hydro MV already making 105kEU (how does that scale up? I don't know).

Is there a computational cost problem with Hydro MV scaled up this much and using so many supply converters to HV? Different issue, but only justification I can see to incentivize Hydro HV is severe performance reasons;  making it possible to avoid Supply Converter.

**Comment by Klaranth** [comment]
Huhhila 
Does pandorabox print the https://github.com/minetest-mirrors/ambience/blob/bffbb1c82291a993d94f0679382e143f9491d55a/soundsets.lua#L106 log line on startup?

**Comment by S-S-X** [comment]
Linking few issues that mostly aim to include shortcuts for speeding up game, reducing required space for machines, making mining or processing simply faster as main goal without providing much anything else: #164 #159 #136 #118 #114 #108 #81
