### ISSUE TITLE
Votebot alternative interfaces

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#126]
Alternative user interfaces for the votebot 

- formspecs  (probably moot by now) 
- voting booth node in Tnet style and access a voting formspec which lists all available votes. Also gives space to gather votes for a referendum. 
- Donate with MG : Most MG in chest for answer wins. 
- Introduce NPC which presents voting options.

**Comment by S-S-X** [comment]
For in game voting using travelnet style formspec (touch screen but you decide what nodes you put around it...) there's https://github.com/pandorabox-io/in-game/tree/master/voting-luac available, it has been used successfully for contest voting (multiple choice answers).

For voting API it would be good to merge vote bot with similar thing I've done for voting luac: basically simple voting API. Functionality is simple, basically just add or migrate similar api to nodered (one I've written was for google firebase: https://github.com/pandorabox-io/in-game/blob/master/voting-luac/firebase-index.js)

**Comment by S-S-X** [comment]
> Donate with MG : Most MG in chest for answer wins.

This will be very hard to get right and most probably is not good way to do voting, pay to vote imo is just wrong way to do voting.

> Introduce NPC which presents voting options.

This would need new NPC that only does voting, in my opinion this is bad idea because there's already multiple ways to allow voting in game.
If however there would be NPC that could allow custom conversation functionality then I could see enough uses for NPC and it could do voting just like how voting-luac or nodered vote bot does.
For example programmable NPC or ability to talk with external API that provides dialogue)

**Comment by OgelGames** [comment]
> NPC that could allow custom conversation functionality

Now that's a cool idea... 🤔

**Comment by OgelGames** [comment]
Moved chat NPC idea to https://github.com/pandorabox-io/mobs_npc/issues/5 (idk when I'll get around to it, but I really want to add it).

Other information can be copied to one of the other issues if necessary.
