### ISSUE TITLE
Add command to change password

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#160]
<brlj> would it be possible to add command for players to change their own password? mobile phone and tablet players have trouble with "press ESC key" process? something like /mypass or something short? also put info in text players with default password get on screen?
BuckarooBanzai 
Possible, but not a good idea: the password would be visible in plaintext over the wire, the ESC-Change-Password option is a safer solution
Huhhila
just checked on android client, "esc" is back-button on the android versions that have such, likely a swipe gesture on those that don't.

**Comment by S-S-X** [comment]
This is not really something that should be fixed through mods or server, problem of this kind should and must be fixed in minetest client to get acceptable results.

It is either UX problem or documentation problem on Minetest engine, basically client user interface problem that cannot be fixed without modifying client application.

If it would be ~fixed~ hacked to work with custom form or chat command it would be just teaching bad habits and bad security practices for everyone and in long run could allow social-engineering kind attacks (through server invites) towards not so tech oriented players.
