### ISSUE TITLE
Allow charging JD with technic lv/mv

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#175]
ThinkSome ; SX 

The lv option could allow different setups where the wireless power transfer node or whatever it is called is used to charge subships from the mothership, so, scout ships would no longer need a technic setup on them, just the JD.

There's many examples for that. Just those are using HV without generators or anything like that on scout ship itself. One example that has only engine and 1 cable is Lava Falls jumpdrive travelnet thing.
That is: jumpdrive engine, 1 digiline wire, 1 technic hv cable (added digi cables after that, could use those to have just 2 nodes inside jumped area for R1 thing)

**Comment by S-S-X** [comment]
LV or MV option does not change any of things request was based on, currently jumpdrive just simply requires HV base station / charging station and does not require any switching stations or generators.
I think this should not be changed, it simply just makes connections too universal.

Because request contains only made up reason that is invalid and does not really contain any useful reason I do believe this is again just another "make game simpler and faster"-request.

**Comment by OgelGames** [comment]
Supply converters exist, it's already possible.

**Comment by Klaranth** [comment]
et 
digiline signal generator
ok so basically have a node that can generate digiline messages at a high interval [like 19 events/s] (could be useful for video games, depends on how it would be implemented)
