### ISSUE TITLE
Technic City Trains planning

### ISSUE THREAD

**Issue by Montandalar** [pandorabox-io/in-game#222]
See the full proposal at [PandoraBox Wiki](https://pandorabox.io/index.php/Technic_City_Trains). I am crossposting here as SX told me this is the typical spot for proposals on the server.

* Are there key stakeholders other than BuckarooBanzay who need to be consulted? Also: Ruggila owns the Harbour.
* Are the station names acceptable? Can you suggest better ones?
* Are the proposed extensions acceptable?
  * New Station 'Beach'
  * New Station 'Harbour' (Metro Stage 2)
  * Snowy End (S-bahn Stage 2)
* Can the areas highlighted red on the map please have access arranged for Blockhead?

**Comment by S-S-X** [comment]
> Are there key stakeholders other than BuckarooBanzay who need to be consulted

Any player who has protected something in areas.
For some thing we can consider removing or moving protected things but mostly if it is something insignificant, this is highly situational and only as last resort (if at all).

> Are the station names acceptable? Can you suggest better ones?

Sounds good for me. Well, almost anything goes if you ask me :)

> Can the areas highlighted red on the map please have access arranged for Blockhead?

Yes and no, there's no need to reserve areas like that and it is harder than protecting areas in world. That's because those areas should be checked anyway.
However you can mark areas with different map markers and probably want to at least add train line markers.

**Comment by S-S-X** [comment]
> Can the areas highlighted red on the map please have access arranged for Blockhead?

For this I'd like to add: if there's some protection problems that needs to be solved ask about it on game chat #reports channel.
We could also add area protections with protect_street privilege if that makes sense but what I've mostly done myself: grab stack of priv protectors and run around with protector placement tool :)
For public projects there's usually players who are willing to donate materials / protectors if needed.

**Comment by Montandalar** [comment]
I ask specifically for access but not necessarily for areas-mod areas to be created. I have to ask because I was unable to access the areas marked in red on the map despite having protect_streets, protect_technic_city_infra and all the necessary advtrains privs. Something else is blocking those so admin needs to resolve.

**Comment by S-S-X** [comment]
Issue is resolved (at least should be..), closing this. Reopen if there's still something that possibly requires extended discussion.
