### ISSUE TITLE
Should JD check altitude of source before jump?

### ISSUE THREAD

**Issue by SwissalpS** [pandorabox-io/in-game#234]
You can currently jump any unprotected area away, but you can't always return unless you already have landing privs.
Wouldn't it make sense to check source altitude too?

**Comment by S-S-X** [comment]
Kind of should be restricted but then also players who did build space ships around ground level but does not yet have XP for unrestricted use cannot anymore move those out.

Should this be communicated somehow / somewhere so that it would be (bit more) clear before ship is already built?
Of course players with higher XP can help moving ship out of protected zone, would this be enough?

**Comment by SwissalpS** [comment]
possibly we could add an on_place override of engines. therin check priv and output chat message.

Currently player needs moon_access to be able to read the basic JD tutorial. This may seam like a progress guide. What often happens, is that users just try on their own and even later when they have the XP, they have forgotten to go check the tutorials again.

In a nutshell, no matter how prominent the tutorials explain this particular detail, users tend to not read well, a warning in chat might have a little more chance of being noticed.

"You need x more XP to be able to jump away from here"

**Comment by BuckarooBanzay** [comment]
fixed by https://github.com/pandorabox-io/pandorabox_custom/pull/47
