### ISSUE TITLE
New Beacon Buff : Satiation 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#258]
baijin
3 levels of satiation buffs on beacons, its possible to starve to death in only a few seconds with crafting activity.

**Comment by SwissalpS** [comment]
isn't that what we want? Encourage players to use autocrafters.
The topic of auto-eating has been discussed at length.
See any topic about beacons or healing

**Comment by S-S-X** [comment]
Beacons should not be able to keep player alive when there's any lethal effects affecting player. Beacon effects were carefully tuned to not allow excessive healing or similar effects, beacons are not meant to make players immortal and effects should at most reduce negative effects (like healing beacon which wont keep player alive but is still providing passive healing as long as player is not losing health).

This is very much intentional, there's creative servers to skip crafting restrictions and servers with damage disabled to skip deaths. There's been enough discussion about this to just close request right away.

**Comment by Klaranth** [comment]
Blockhead
From Jennison via LiberaChat: "I wish there could be a feature of hunger in the beacon" 
Me: To disable getting hungry. Jennison: "yea In a certain range"

OgelGames 
Short answer, no, long answer, see SX's comment here: https://github.com/pandorabox-io/in-game/issues/258

Blockhead
It could perhaps remove only the hunger loss from time but not crafting.. but eating isn't really hard

**Comment by Klaranth** [comment]
Marsufoman
Can crafting PLEASE not use so much food, my hunger bar basically DEPLETES every time. It is SO INCREDIBLY annoying.

Hedgehog
That's why we have autocrafters.
