### ISSUE TITLE
Re-instate death penalty 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#264]
Hedgehog 
Reinstate death penalty of -1K or -2K XP on death.

**Comment by Klaranth** [comment]
See also 👍 https://github.com/pandorabox-io/pandorabox.io/issues/228

**Comment by S-S-X** [comment]
SX: one simple way to make it bit better without time based ratelimiters would be to reduce xp only if last change was not also reduction, that would however disable it completely if player wont do anything that gives xp between deaths
SX: basically allow death penalty only if player gained at least 1xp since last death penalty
SX: time based limiter is harsher for afk accounts while xp change based limiter wont care if player is afk or not so which one is better depends on goals
SX: time based should be good enough but afk players were actually reason to disable penalty in first place
SX: Could reintroduce first with -100 XP with current builtin 1 minute rate limiter.
SwissalpS: I'm in favor of the 1xp resetting limiter and have no preference for the amount of deduction

**Comment by SwissalpS** [comment]
I'm also fine with not re-instating xp-penalty, it adds very little to the game.

**Comment by OgelGames** [comment]
If we think of XP as what it's abbreviating, experience, then dying should increase it, because you are experiencing death :P

In other words, I disagree with re-instating the penalty.

**Comment by S-S-X** [comment]
> If we think of XP as what it's abbreviating, experience, then dying should increase it, because you are experiencing death :P

Or you clearly were not experienced enough to avoid death and should therefore lose experience points. (reasoning like this is not really valid and can be used to "prove" anything)

**Comment by MCLV-pandorabox** [comment]
I see XP used here mainly as a method of proving that you are experienced enough to handle certain responsibilities /privs
So a XP penalty for dying makes no sense in this respect.

But if you want to make pandorabox more like a survival experience where you have to fight to survive,only the strong survive, much more like real life, then I totally understand.

But then all players should start right back at 0 for it to be fair. And then I think that many of the people that mainly build beautiful things,and gather resources to do so, will  be leaving. As will I, because that's not what I'm here for, that's what I try to escape by being here.

I vote No on proposition 264

**Comment by S-S-X** [comment]
> But then all players should start right back at 0 for it to be fair. And then I think that many of the people that mainly build beautiful things,and gather resources to do so, will be leaving. As will I, because that's not what I'm here for, that's what I try to escape by being here.

Note that death penalty was there but were disabled due to bug that in certain situation caused repeated deaths while while already dead and through that made player lose huge amounts of XP (and death counter jumping up).
Almost every high XP player did play with death penalty from beginning and having or not having death penalty did not seem to affect player base or play style in any significant way.

**Comment by MCLV-pandorabox** [comment]
It doesn't really matter to me how things used to be before I joined. Lots of things used to be worse in the past, and got improved. As far as I'm concerned, this is one of them.

I think it's hard enough already to get to the level of XP to reach for instance jumpdrive_land privs without having to worry about dying, loosing that and stranding half your fleet.
Sure it would make it more "Game". But I'm not interested in that. I still consider myself a developer and I would like to "build" cool applications without having to spend most my time XP digging before I can do that.
Sure I need experience in what the game is all about and follow a reasonable career path to figure out what kind of things would be handy to develop, but that should be a one time thing, not something to maintain imo.

**Comment by OgelGames** [comment]
I don't see this happening any time soon, closing.
