### ISSUE TITLE
replacer.deny_list upgrade

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#278]
Huhhila
SwissalpS: Consider splitting replacer.deny_list into two (from/to). Currently wanting to replace a node that happens to be holding water still with a protblock... having that denied makes the process unnecessarily complicated.

SX 
For replacer.deny_list is there any real reason for from/to blacklists? For me having protection stuff blacklisted seems to be more just in case than any real reason.
I do also think that having separate from/to blacklists might cause more problems than what it would be solving simply because of not allowing to go back / replace again after using replacer with semi blacklisted nodes.

Huhhila
... so a yes-I-know-I-am-shooting-myself-in-foot mode would be useful than separate from/to?

SX 
I think so yes and blacklists more for disallowing really over powered things / getting otherwise unobtainable items / crashing server.

**Comment by SwissalpS** [comment]
I'm not convinced about splitting into two lists.
The protectors are added by default because of the not undoable situation and a little because not wanting to allow players to place a carpet of protectors. It would need testing to see if that couldn't be some kind of lag/attack vector.
If it turns out to be no problem, we can remove protectors for pandorabox.

In short, I left it in from a 'better safe than sorry' mentality.

**Comment by Klaranth** [comment]
MCLV
Undo function for replacer

**Comment by SwissalpS** [comment]
don't intend to implement either ideas (any time soon)
