### ISSUE TITLE
Allow increasing beacon effect range based on player XP

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#3]
Can we implement beacons with higher radius? Instead of 50 say 150? 
Or basically different beacons to craft with higher radius?

**Comment by Klaranth** [comment]
Reply from SX on Discord:
"beacons with higher radius?"
Not doable currently, actually radius 50 also is not reliably possible on pandorabox.

**Comment by S-S-X** [comment]
Mapblock activation range is what currently limits beacon effects, this cannot be increased indefinitely and causes higher server lag because a lot larger area around every player becomes active.

This does not however make this impossible to implement.
By *"not doable"* I meant more that it will require significant amounts of work and cannot be just applied to current beacons as better effect.

**Comment by FeXoR-o-Illuria** [comment]
XP should be mostly a measure of what players can handle (e.g. moon access) and what they can be trusted with (e.g. place lava) and less something to get rewards for IMO.

**Comment by Klaranth** [comment]
At 500K XP you can create larger protected areas, but you are still having to litter the place with beacons. 
Having a beacon that can handle a bigger area to complement the bigger protection area, makes sense.

**Comment by OgelGames** [comment]
Closing as per SX's comment.
