### ISSUE TITLE
Nuclear powered vacuum / chainsaw / replacer 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#301]
Naso 
Idea: nuclear vacuum cleaner. 20x battery charge. Recipe could include a nuclear reactor or uranium rods. I think the range is fine but could be a +2 or +4.
It's mostly a convenience item so it doesn't have to be charged as often.

Hedgehog
Nuclear reactor might not work, ...radiation and such. The rods might work, if you replace them from the item with new ones....

Perhaps two recipes. One for a nuclear rod enabled vacuum, and one with the magazine / uranium rod you can attach to it to make it work ?
Then the magazine / uranium rod should be usable as well with a nuclear powered chain saw, and a nuclear powered replacer ?

Naso
Nuclear replacer set to crust, sounds like the kind of thing that would be harder to clean than an actual nuclear spill LOL
Nuclear chainsaw sounds so metal and now I want one too haha

I don't know how I feel about actually having to feed nuclear rods to them. Maybe uranium lumps, much like JDs eat mese? And keep the ability to charge them normally. unless that's too much convenience :p

Hedgehog
You think you can create the images for the item, too ? :) it has to look different than the normal kind ....

Naso 
yep

**Comment by El-Naso** [comment]
Recipe
![image](https://user-images.githubusercontent.com/75192588/175790356-735f88ab-bc6b-447f-b4c0-f44ed6b57a88.png)

**Comment by SwissalpS** [comment]
once a nuclear reaction is started, it keeps going. When not using the heat to generate electricity, the heat would have to be dispersed some other way. These devices would probably be way too hot to hold and may melt away.
One rod would last a lifetime, so no need for recharging. The machinery would probably not resist a second round.
Wear would have to be calculated since craft-time or first time used.

It's fun as a joke, can't see how this could be implemented seriously and still be fun :D

**Comment by El-Naso** [comment]
Tentative texture. Might update it later, hopefully it does ok for the time being ^^
![technic_vacuum_nuclear](https://user-images.githubusercontent.com/75192588/175796078-51102253-0fdf-4f0e-b81f-13a10269e993.png)
Have a preview as well:
![image](https://user-images.githubusercontent.com/75192588/175796372-23927940-b52a-448e-b149-ecccc682b63f.png)

**Comment by S-S-X** [comment]
> once a nuclear reaction is started, it keeps going. When not using the heat to generate electricity, the heat would have to be dispersed some other way. These devices would probably be way too hot to hold and may melt away.

Probably, if actually done, it would consist of few main components:

* huge capacitors to store power needed to operate device
* nuclear battery to slowly charge capacitors all the time
* heat sink depending on how fast capacitors are charged: how much energy you need to get rid of when capacitors are fully charged
* motor that will require high power for short time when device is operated

Basically it would be like regular vacuum / chainsaw / whatever but a lot heavier and instead of charging in battery box you simply cannot use it for a while until it is recharged from nuclear battery.
You cannot power devices like that directly from nuclear battery:

* Device can be used only when capacitors are charged to deliver required peak power for motor
* After using device you'll need to put it aside for a while because device cannot be used at all before capacitors have been recharged
* After capacitors have been recharged devices starts heating up and gets rid of excess energy using heat sinks
* If you're in vacuum with it it will either need large high tech radiators or it will melt itself

Devices that could work directly with nuclear battery without too much hand waving would be:
* radar
* always on lights
* any low power device that operates continuously and required energy is constant

**Comment by SwissalpS** [comment]
if this is just about having more charge, why not an mk2 upgrade recipe: bec = blue energy crystal

bec bec bec
bec tool bec
bec bec bec

**Comment by OgelGames** [comment]
Nuclear powered tools don't really make sense IMO, you'd have to wear a hazmat suit to use them :P

MK2 and MK3 tools are definitely an option though, someone even made a mod for it already: https://content.minetest.net/packages/Mineminer/technic_addons/

**Comment by S-S-X** [comment]
> Nuclear powered tools don't really make sense IMO, you'd have to wear a hazmat suit to use them :P

Mostly makes sense as experiment, somewhat science based nuclear powered tools would change workflow but would not be clearly better than current tools. You would not need to use battery boxes but you would still need to recharge tools.

Experimental tools like that could be easily added without adding any new items and could also be removed by just removing code effectively converting nuclear powered tools back to their regular counterparts.

If someone wants to make experiment like that then it is just some additional metadata and calculations for current tools.
Removal is then as easy as installing mod version without nuclear battery feature.
Basically recipe for same tool but with metadata marker making it nuclear powered variant.

> MK2 and MK3 tools are definitely an option though, someone even made a mod for it already:

I've tested those a little and will strongly recommend against those tools, those tools feel overpowered even in creative setting.
Especially chainsaw will for sure cause a lot more harm than good (tested that bit more than other tools, mk3 is even included in mt-mods Technic test set).

Do extensive testing before adding any of those and also remember that code is copy pasted from some very old Technic release: there will be bugs / missing features that have been fixed with latest base tools.

**My personal opinion about whole request and discussion so far:**
Not needed, if current tools are not good enough then instead of adding BadTool Pro MkX determine if capabilities should be upgraded.
Adding more MkX variants will only cause deprecation of previous tools, things like "wooden sword", "iron sword", "copper sword", "mese sword", "gold sword", "diamond sword" and so on are not needed or useful.

Either make it behave in different manner or fix issues with current tools instead of adding uninteresting linear speed+durability upgrade.
Nuclear battery changes behavior a bit but not very much.

**Comment by OgelGames** [comment]
> Adding more MkX variants will only cause deprecation of previous tools, things like "wooden sword", "iron sword", "copper sword", "mese sword", "gold sword", "diamond sword" and so on are not needed or useful.

I disagree, lower level tools will always have some use, albeit less than the highest level.

However, in the case of technic tools, adding higher capacity tools would make powerbanks less useful, as they we created specifically for extending the time you could use tools away from a technic network.

**Comment by S-S-X** [comment]
> I disagree, lower level tools will always have some use, albeit less than the highest level.
> 
> However, in the case of technic tools, adding higher capacity tools would make powerbanks less useful, as they we created specifically for extending the time you could use tools away from a technic network.

Almost everything has always some use, that's not the point. Point is that adding a lot of linear upgrades through +speed, +durability, +reach and so on is not useful way to bring new content into game.

Doing that however will always have some uses: cheaper tools can be used where more expensive is not needed.
I bet you cannot find real use where copper sword would be required when you have diamond sword other than different texture or can you?
