### ISSUE TITLE
A better screwdriver mod

### ISSUE THREAD

**Issue by Kimapr** [pandorabox-io/in-game#316]
MTG's builtin screwdriver (and technic's screwdriver, which is built on same principles) is very unintuitive and unpredictive. Would be better if we get a more intuitive alternative, like https://content.minetest.net/packages/entuland/rhotator/ . This will improve building experience very much and reduce overall screwdriver wearing

**Comment by S-S-X** [comment]
Another request for this and I know many other players have asked for rotation clone functionality.

Maybe simplest way to easily get this functionality would be through adding another mode for technic replacer, one that simply ignores node name and reuses node in world instead of attempting to take item from inventory. Basically just place exact same node again and for that use what replacer already has (a lot of compatibility stuff and such).

**Comment by SwissalpS** [comment]
> Maybe simplest way to easily get this functionality would be through adding another mode for technic replacer, one that simply ignores node name and reuses node in

already exists and active for months :D
You can change settings via formspec or modifier keys between modify both, only param2 or only node keeping param2 from world

**Comment by OgelGames** [comment]
I've already got a mostly working mod for this, just need to implement the different rotation modes: https://github.com/OgelGames/omnidriver (repo is private currently, but it's there)

![omnidriver-export](https://github.com/pandorabox-io/in-game/assets/48543043/d4aaaeb7-5b01-4340-b269-4f614a04f9fa)

I guess it's about time I finish it...
