### ISSUE TITLE
Masks

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#33]
BuckarooBanzai — 04/25/2021
https://content.minetest.net/packages/GenesisMT/mask/ (thx for the hints SX :wink: )
Mask
A simple mask you can wear.

**Comment by S-S-X** [comment]
Few days ago looked up numbers to allow comparing with current armors, mask is top tier head gear that breaks very easily.
It wont cause additional lag and is very simple mod, if some players do want it I think it could be just added.

(I think some numbers commented on #ideas channel, look there if interested)

Could start public vote about that in game with announcement to see if there's players who would be interested to have masks.

**Comment by OgelGames** [comment]
Well personally I don't think things like this should be added, mainly just to keep pandorabox free of controversial real world subjects.

I'm sure there's at least some players that would really dislike that mod.

**Comment by S-S-X** [comment]
> Well personally I don't think things like this should be added, mainly just to keep pandorabox free of controversial real world subjects, I for one don't want to be reminded about such things while playing a game.

I see this bit differently mostly because I don't see it as controversial real world subject, it is true that masks are used a lot more in countries where masks were not used that much before. I think probably main reason why I don't see masks in game controversial is simply that I don't see masks in real world controversial subject but you're probably right that there's different views on this.

There might be a lot of different views on this and I think it would be fair to ask unless it is clear already that multiple players would outright hate this mod as there's nothing controversial in how mod works technically and it is simple enough that technical or game balance problems with mod are practically zero.

> Also I'm sure there's at least some players that would really dislike that mod...

For this voting should give some numbers too, I think it would be good to stress point that voting against is important too.

> I for one don't want to be reminded about such things while playing a game.

For this, if you personally absolutely don't want to and would not be okay with it even if everyone else would vote for it then I'd say simply leave it out.
However if you're more thinking about what others might think about it then I'd say there should be public voting to find out what other players really think about it.

**Comment by OgelGames** [comment]
Let's just do the voting. Yes I don't want it added, but I can also just make it invisible with a texture pack anyway.

**Comment by Klaranth** [comment]
So, how do we set up a public voting for this? ( And later on for other issues? )

**Comment by Klaranth** [comment]
Votes as of August 8 2021 

Add masks : 
Yes 2 
No 4

@BuckarooBanzay
@S-S-X
