### ISSUE TITLE
Instantly empty backpack option 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#80]
orekart
Add a button to the large backpack with "X" like in the crafting area, that returns contents to inventory and/or how Gold Chest does it to move all items of type.

SX
Drops everything to ground and random chance for few hairballs

**Comment by Klaranth** [comment]
@OgelGames  @S-S-X  
Is this doable to implement or more likely non-trivial?
When the former, please move it forward, when the latter, close the issue.

**Comment by S-S-X** [comment]
> Is this doable to implement or more likely non-trivial?

It is doable. Fairly simple with chat command, bit more work if adding button to inventory GUI.

**Comment by OgelGames** [comment]
I would definitely like to see this added, and I don't think it would be too hard to add, though it wouldn't be as advanced as technic chests, mainly due to formspec space limitations.

Also still need to test the recent updates to `unified_inventory`: https://github.com/pandorabox-io/pandorabox-mods/pull/1712 👀

**Comment by OgelGames** [comment]
Closing for the same reason as #339 (basically the same thing)
